version: '3'
services:
  bd:
    container_name: basededatos
    image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $PASSBD
    volumes:
      - $VOLUMES/databd:/var/lib/mysql
    ports:
      - "3306:3306"
        
  adminerbd:
    container_name: adminerbd
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8086:80"
