version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: postgress
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - $PWD/postgresql:/var/lib/postgresql
      - $PWD/postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    restart: always
    container_name: sonarqube
    ports:
      - "9005:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - $PWD/sonarqube_conf:/opt/sonarqube/conf
      - $PWD/sonarqube_data:/opt/sonarqube/data
      - $PWD/sonarqube_extensions:/opt/sonarqube/extensions
      - $PWD/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins


networks:
  sonarnet: