version: '3'
services:
   gitlab:
      container_name: gitlab
      image: gitlab/gitlab-ce:14.5.4-ce.0
      ports:
         - "8085:80"
      volumes:
         - $VOLUMES/gitlab/config:/etc/gitlab
         - $VOLUMES/gitlab/logs:/var/log/gitlab
         - $VOLUMES/gitlab/data:/var/opt/gitlab
   gitlab-runner:
      container_name: gitlab-runner
      image: gitlab/gitlab-runner:ubuntu
      volumes:
         - $VOLUMES/gitlab/gitlab-runner/config:/etc/gitlab-runner
         - /var/run/docker.sock:/var/run/docker.sock
