version: '3'
services:
   jenkins:
      container_name: jenkins
      image: jenkins/jenkins:slim-jdk8
      ports:
         - "8082:8080"
      volumes:
         - $VOLUMES/jenkins:/var/jenkins_home
